# Generated by Django 4.0.4 on 2022-09-30 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='PostImages',
        ),
    ]
