# Generated by Django 4.0.4 on 2022-09-30 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postimage_post_image_delete_postimages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
