# Generated by Django 4.0.4 on 2022-05-01 10:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_students_student_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(default=' ', upload_to='')),
                ('first_name', models.CharField(default=' ', max_length=20)),
                ('last_name', models.CharField(default=' ', max_length=20)),
                ('pincode', models.PositiveIntegerField(default=' ', validators=[django.core.validators.MaxValueValidator(15)])),
                ('age', models.IntegerField(default=' ', validators=[django.core.validators.MaxValueValidator(3)])),
                ('intrested_exam', models.CharField(choices=[('10th board cbse', '1OTH BOARD CBSE'), ('11th board cbse', '11TH BOARD CBSE'), ('12th board cbse', '12TH BOARD CBSE'), ('8th board cbse', '8TH BOARD CBSE'), ('9th board cbse', '9TH BOARD CBSE'), ('iit jee', 'IIT JEE'), ('iit jee advance', 'IIT JEE ADVANCED'), ('Neet', 'NEET'), ('Upsc', 'UPSC'), ('Sat', 'SAT'), ('Ielts', 'IELTS')], default='10th board cbse', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='students',
        ),
    ]
