# Generated by Django 4.0.4 on 2022-05-01 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_details_delete_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='age',
            field=models.PositiveIntegerField(default=' ', validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
