# Generated by Django 4.0.4 on 2022-05-01 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_student_details_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='age',
            field=models.PositiveIntegerField(default=' ', validators=[django.core.validators.MaxLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='pincode',
            field=models.PositiveIntegerField(default=' ', validators=[django.core.validators.MaxLengthValidator(15)]),
        ),
    ]
