# Generated by Django 4.0.4 on 2022-05-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_student_details_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='age',
            field=models.CharField(default=' ', max_length=2),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='pincode',
            field=models.CharField(default=' ', max_length=15),
        ),
    ]
