import datetime
AWS_ACCESS_KEY_ID = "AKIAW4NP5ENFLPTBZ6SJ"
AWS_SECRET_ACCESS_KEY = "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"
AWS_FILE_EXPIRE = 200
AWS_PRELOAD_METADATA = True
AWS_QUERYSTRING_AUTH = True
AWS_DEFAULT_ACL = None

DEFAULT_FILE_STORAGE = 'aws.utils.MediaRootS3Boto3Storage'
STATICFILES_STORAGE = 'aws.utils.StaticRootS3Boto3Storage'
AWS_STORAGE_BUCKET_NAME = "allquestionpaper"

AWS_S3_REGION_NAME = "ap-south-1"

# AWS_S3_SIGNATURE_VERSION = "s3v4"

